# Generated by Django 4.0.6 on 2022-08-23 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemid', models.CharField(max_length=50, unique=True)),
                ('ItemName', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
                ('Availability', models.BooleanField(default=True)),
            ],
        ),
    ]
